---
- name: Gather OS-Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - main.yml

- name: Install dependencies
  become: true
  when: ansible_os_family == "Debian"
  with_items: "{{ dependencies }}"
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest

- name: Install Aquatone
  become: true
  gem:
    name: aquatone
    state: latest
    user_install: no
